export const mockAutoCamionetaTableModelParteExternaBase: any = [
  {
    id: 1,
    parteExterna: 'FAROS BUSCAHUELLAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 2,
    parteExterna: 'FAROS DELANTEROS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 3,
    parteExterna: 'LUZ ALTA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 4,
    parteExterna: 'LUZ BAJA',
    estadoTable: 'BUENO',
    observaciones: '',
  },

  {
    id: 5,
    parteExterna: 'GUIÑOS DELANTEROS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 6,
    parteExterna: 'PARRILLA DELANTERA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 7,
    parteExterna: 'CAPOT',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 8,
    parteExterna: 'PARAGOLPE DELANTERO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 9,
    parteExterna: 'GUARDAB. DEL. DER.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 10,
    parteExterna: 'GUARDAB. DEL  IZQ.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 11,
    parteExterna: 'PUERTA DEL. DERECHA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 12,
    parteExterna: 'PUERTA DEL. IZQUIERDA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 13,
    parteExterna: 'PARABRISAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 14,
    parteExterna: 'PUERTA TRAS. DERECHA',
    estadoTable: 'BUENO',
    observaciones: '',
  },

  {
    id: 15,
    parteExterna: 'PUERTA TRASERA IZQ.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 16,
    parteExterna: 'LUNETA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 17,
    parteExterna: 'TAPA BAUL',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 18,
    parteExterna: 'CAJA DE CARGA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 19,
    parteExterna: 'GUARDAB. TRAS. IZQ.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 20,
    parteExterna: 'GUARDAB. TRAS. DER',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 21,
    parteExterna: 'PARAGOLPES TRASERO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 22,
    parteExterna: 'BARRAL LUMINICO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 23,
    parteExterna: 'LEVANTA VIDRIOS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 24,
    parteExterna: 'APOYA MANOS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 25,
    parteExterna: 'PARLANTES',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 26,
    parteExterna: 'STEREO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 27,
    parteExterna: 'PARASOLES',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 28,
    parteExterna: 'TAPIZADO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 29,
    parteExterna: 'CIERRE CENTRALIZ.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 30,
    parteExterna: 'VOLANTE',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 31,
    parteExterna: 'BOCINA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 32,
    parteExterna: 'GUANTERA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 33,
    parteExterna: 'PALANCA CAMBIOS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 34,
    parteExterna: 'LLAVE LUCES',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 35,
    parteExterna: 'ALFOMBRAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 36,
    parteExterna: 'CINTURON SEGUR.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 37,
    parteExterna: 'MANIJAS PUERTAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 38,
    parteExterna: 'ESPEJO RETROVISOR',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 39,
    parteExterna: 'REGULADOR VOLANTE',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 40,
    parteExterna: 'PEDALERA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 41,
    parteExterna: 'REJA DIVISORIA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 42,
    parteExterna: 'TABLERO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 43,
    parteExterna: 'ODOMETRO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 44,
    parteExterna: 'ASIENTOS DELANT.',
    estadoTable: 'BUENO',
    observaciones: '',
  },

  {
    id: 45,
    parteExterna: 'ASIENTOS TRAS.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 46,
    parteExterna: 'CONSOLA LUMINICA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 47,
    parteExterna: 'ANTENA DE RADIO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 48,
    parteExterna: 'CHAPAS PATENTES',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 49,
    parteExterna: 'ESPEJO DEL DERECHO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 50,
    parteExterna: 'ESPEJO DEL IZQUIERDO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 51,
    parteExterna: 'ESCOBILLAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 52,
    parteExterna: 'MANIJAS PUERTAS DEL.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 53,
    parteExterna: 'MANIJAS PUERTAS TRAS.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 54,
    parteExterna: 'CERRADURAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 55,
    parteExterna: 'MANIJA PORTON TRAS.',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 56,
    parteExterna: 'RUEDA DE AUXILIO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 57,
    parteExterna: 'VIDRIO DEL. DERECHO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 58,
    parteExterna: 'VIDRIO DEL. IZQUIERDO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 59,
    parteExterna: 'VIDRIO TRAS. DERECHO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 60,
    parteExterna: 'VIDRIO TRAS. IZQUIERDO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 61,
    parteExterna: 'PLOTEO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 62,
    parteExterna: 'R.O. VISIBLE',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 63,
    parteExterna: 'NOMBRE DE PENDENCIA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 64,
    parteExterna: 'ELEMENTOS DE SEGURIDAD',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 65,
    parteExterna: 'BALIZA SEÑALIZADORA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 66,
    parteExterna: 'MATAFUEGO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 67,
    parteExterna: 'CRIQUET',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 68,
    parteExterna: 'LLAVE DE RUEDA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 69,
    parteExterna: 'BOTIQUIN ',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 70,
    parteExterna: 'BALIZA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 71,
    parteExterna: 'SIRENA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 72,
    parteExterna: 'MOTOR',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 73,
    parteExterna: 'BATERIA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 74,
    parteExterna: 'BOCINA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 75,
    parteExterna: 'BOMBA NAFTA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 76,
    parteExterna: 'BOMBA AGUA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 77,
    parteExterna: 'CAJA DE CAMBIOS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 78,
    parteExterna: 'BOMBA INYECTORA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 79,
    parteExterna: 'BOMBA FRENO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 80,
    parteExterna: 'BUJIAS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 81,
    parteExterna: 'ALTERNADOR',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 82,
    parteExterna: 'CORREA VENTILADOR',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 83,
    parteExterna: 'BOBINA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 84,
    parteExterna: 'FILTROS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 85,
    parteExterna: 'CARDAN',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 86,
    parteExterna: 'INYECTORES',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 87,
    parteExterna: 'PALIERES',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 88,
    parteExterna: 'CREMALLERA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 89,
    parteExterna: 'MOTOR ARRANQUE',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 90,
    parteExterna: 'MOTOR LIMPIA PARABR.',
    estadoTable: 'BUENO',
    observaciones: '',
  },

  {
    id: 91,
    parteExterna: 'RADIADOR',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 92,
    parteExterna: 'FRENO ABS',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 93,
    parteExterna: 'VARILLA MEDICION',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 94,
    parteExterna: 'BOMBA HIDRAULICA',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 95,
    parteExterna: 'AIRE ACONDICIONADO',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 96,
    parteExterna: 'ELECTROVENTILADOR',
    estadoTable: 'BUENO',
    observaciones: '',
  },
  {
    id: 97,
    parteExterna: 'DIFERENCIAL',
    estadoTable: 'BUENO',
    observaciones: '',
  },
];
