export const mockMotosTableModelParteExternaBase: any = [
  {
    id: 1,
    parteExterna: 'LEVA MANDO DE CAMBIOS',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 2,
    parteExterna: 'ORQUILLA BALIZA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 3,
    parteExterna: 'CAÑO DE ESCAPE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 4,
    parteExterna: 'GUARDABARRO TRASERO',
    estadoTable: 'B',
    observaciones: '',
  },

  {
    id: 5,
    parteExterna: 'LEVA DE FRENO DELANTERO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 6,
    parteExterna: 'CALLIPER TRASERO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 7,
    parteExterna: 'LEVA DE MANDO EMBRAGUE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 8,
    parteExterna: 'TABLERO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 9,
    parteExterna: 'PEDAL FRENO TRASERO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 10,
    parteExterna: 'COMANDO BALIZA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 11,
    parteExterna: 'BULBO DE STOP',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 12,
    parteExterna: 'BALIZA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 13,
    parteExterna: 'MULETA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 14,
    parteExterna: 'SIRENA',
    estadoTable: 'B',
    observaciones: '',
  },

  {
    id: 15,
    parteExterna: 'CABALLETE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 16,
    parteExterna: 'SIRENA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 17,
    parteExterna: 'DEFENSA  DELANTERA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 18,
    parteExterna: 'RUEDA DELANTERA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 19,
    parteExterna: 'PUÑO ACELERADOR',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 20,
    parteExterna: 'RUEDA TRASERA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 21,
    parteExterna: 'TAPA TANQUE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 22,
    parteExterna: 'ESPEJOS',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 23,
    parteExterna: 'TANQUE COMBUSTIBLE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 24,
    parteExterna: 'TANQUE DE COMBUSTIBLE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 25,
    parteExterna: 'CACHAS CON INSIGNIA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 26,
    parteExterna: 'MANOPLAS',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 27,
    parteExterna: 'MANUBRIO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 28,
    parteExterna: 'FRENO DE MANO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 29,
    parteExterna: 'CARENADO CON PARABRISA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 30,
    parteExterna: 'AMORTIGUADORES',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 31,
    parteExterna: 'PLOTEO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 32,
    parteExterna: 'CADENA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 33,
    parteExterna: 'PLOTEO RO/NI/NO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 34,
    parteExterna: 'FISP. DE FRENO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 35,
    parteExterna: 'HERRAMIENTAS',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 36,
    parteExterna: 'ASIENTO CON CERRADURA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 37,
    parteExterna: 'DOCUMENTACION',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 38,
    parteExterna: 'BOCINA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 39,
    parteExterna: 'CHAPA PATENTE',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 40,
    parteExterna: 'FAROS INTERMITENTES',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 41,
    parteExterna: 'TARJETA',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 42,
    parteExterna: 'FARO DELANTERO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 43,
    parteExterna: 'LLEVES DE CONTACTO',
    estadoTable: 'B',
    observaciones: '',
  },
  {
    id: 44,
    parteExterna: 'FARO TRASERO',
    estadoTable: 'B',
    observaciones: '',
  },
];
